[package]
name = "rocket-learn"
version = "0.1.0"
authors = ["zhaoyenb <116682877@qq.com>"]

[dependencies]
rocket = "0.3.8"
rocket_codegen = "0.3.8"
markdown = "0.2.0"
comrak = "*"
websocket = "0.20.2"
