[production]
menu_path = "/usr/local/nginx/html/docs/"
books = [ { name = "effective java(英文版)"    , path = "effective-java.pdf" },
          { name = "es3规范(中文版)"           , path = "es3.pdf" }, 
          { name = "es1规范(英文版)"           , path = "es1.pdf" }, 
          { name = "expert-c.pdf(英文版)"      , path = "expert-c.pdf" }, 
          { name = "flex和bison.pdf(中文版)"   , path = "flex-bison.pdf" }, 
          { name = "设计模式四人帮版(英文版)"   , path = "partten.pdf" }, 
          { name = "rust-book第二版翻译版本"    , path = "rust-book" } ]