[production]
menu_path = "/usr/local/nginx/html/docs/"
books = [ { name = "effective java(英文版)"    , path = "effective-java.pdf" },
          { name = "es3规范(中文版)"            , path = "es3.pdf" }, 
          { name = "es1规范(英文版)"            , path = "es1.pdf" }, 
          { name = "expert-c.pdf(英文版)"       , path = "expert-c.pdf" }, 
          { name = "flex和bison.pdf(中文版)"    , path = "flex-bison.pdf" }, 
          { name = "设计模式四人帮版(英文版)"    , path = "partten.pdf" }, 
          { name = "rust-book第二版翻译版本"    , path = "rust-book" },
          { name = "SICP"                      , path = "sicp.pdf" },
          { name = "线性代数"                   , path = "线性代数.pdf" },
          { name = "CSAPP(英文版)"              , path = "csapp.pdf" } ]
articles = [
    { tag = "h5", years = [
        { year = "2018", months = [
            { month = "09", articles = [ 
                { name = "wiki类型系统笔记", portrait= "", intro= "阅读Wikipedia上的类型系统的词条，翻译并记录笔记" },
                { name = "ES1规范读书笔记 (一)", portrait= "", intro= "概览" },
            ]},
            { month = "04", articles = [ 
                { name = "Promise讲解", portrait= "", intro= "一个关于promise原理的介绍，同时附上一份符合promise/A+官方800+ test case的实现源码。" },
            ]}
        ]}
    ]}
]